import { Fraunces, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

// Configure Fraunces for display/headings (often used as serif/display)
const fraunces = Fraunces({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-fraunces",
  subsets: ["latin"],
});

// Configure DM Sans for body/primary text (often used as sans-serif)
const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${fraunces.variable} font-sans antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
